### ISSUE TITLE
GUI Missing Errors

### ISSUE THREAD

**Issue by WildKarrade** [ArtixAllMighty/Paintings--#44]
The following errors occurred with The One Probe, about 70% of the time the GUI will not show but you can still click invisable buttons to select paintings.

[17:55:08] [Render thread/FATAL]: Preparing crash report with UUID 260280a8-f6d4-4d43-bcb0-221e2ae6d34d
[17:55:08] [Render thread/ERROR]: Error rendering entity!
net.minecraft.crash.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:361) ~[?:?]
	at mcjty.theoneprobe.rendering.RenderHelper.renderEntity(RenderHelper.java:66) [?:1.16-3.0.7]
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.renderEntity(ElementEntityRender.java:184) [?:1.16-3.0.7]
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:72) [?:1.16-3.0.7]
	at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:68) [?:1.16-3.0.7]
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:42) [?:1.16-3.0.7]
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:42) [?:1.16-3.0.7]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:433) [?:1.16-3.0.7]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:200) [?:1.16-3.0.7]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:86) [?:1.16-3.0.7]
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110) [?:1.16-3.0.7]
	at net.minecraftforge.eventbus.ASMEventHandler_1552_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) [eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634) [?:?]
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:765) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/2000429588.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:41) ~[?:?]
	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:23) ~[?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:310) ~[?:?]
	... 30 more

**Comment by ArtixAllMighty** [comment]
I'll be looking into it, but I fear it's a problem with TOP itself. it seems to have other issues with paintings. 
Try and put up a ticket at his mod too

**Comment by ArtixAllMighty** [comment]
got a picture btw ? i'd love to see the visual issue

**Comment by WildKarrade** [comment]
I will try to get a picture tomorrow or later this evening. The odd thing is it works half the time.

**Comment by Janitor53** [comment]
Video of the issue:
https://user-images.githubusercontent.com/1338646/108858629-6e249900-75fd-11eb-94f1-3afb1c7a426a.mp4
Brass modpack, Forge 36.0.39, paintings-1.16.4-7.0.0.1, theoneprobe-1.16-3.0.7

**Comment by ArtixAllMighty** [comment]
closing issue as issue seems to be fixed on TOP's end.
